version: "3"

services:

  frontend:
    #restart: unless-stopped
    container_name: frontend
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  backend:
    image: django
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/lib/backend/data
    expose:
      - 8001

    
volumes:
    backend:

